[
   {
      "Recession and unemployment":{
         "Total Global":2,
         "USA ":0,
         "Canada":3,
         "Argentina":1,
         "Brazil ":2,
         "Mexico":4,
         "France":1,
         "Germany":1,
         "Italy":0,
         "Spain":3,
         "Sweden":0,
         "UK":4,
         "Czech Republic":2,
         "Poland":2,
         "Russia":4,
         "Turkey":3,
         "Egypt":2,
         "South Africa":4,
         "Australia":3,
         "China":1,
         "India":2,
         "Indonesia":4,
         "Japan":1,
         "South Korea":2,
         "Taiwan":2,
         "Thailand":1
      }
   },
   {
      "Inflation and high prices":{
         "Total Global":4,
         "USA ":0,
         "Canada":0,
         "Argentina":0,
         "Brazil ":0,
         "Mexico":0,
         "France":0,
         "Germany":3,
         "Italy":0,
         "Spain":0,
         "Sweden":0,
         "UK":0,
         "Czech Republic":3,
         "Poland":0,
         "Russia":3,
         "Turkey":1,
         "Egypt":0,
         "South Africa":0,
         "Australia":0,
         "China":0,
         "India":1,
         "Indonesia":0,
         "Japan":0,
         "South Korea":4,
         "Taiwan":0,
         "Thailand":0
      }
   },
   {
      "Money enough to live right and pay the bills":{
         "Total Global":3,
         "USA ":3,
         "Canada":1,
         "Argentina":0,
         "Brazil ":0,
         "Mexico":0,
         "France":2,
         "Germany":4,
         "Italy":0,
         "Spain":0,
         "Sweden":0,
         "UK":3,
         "Czech Republic":0,
         "Poland":0,
         "Russia":2,
         "Turkey":0,
         "Egypt":0,
         "South Africa":0,
         "Australia":4,
         "China":4,
         "India":0,
         "Indonesia":0,
         "Japan":0,
         "South Korea":0,
         "Taiwan":0,
         "Thailand":4
      }
   },
   {
      "Crime and lawlessness":{
         "Total Global":1,
         "USA ":1,
         "Canada":2,
         "Argentina":2,
         "Brazil ":1,
         "Mexico":1,
         "France":4,
         "Germany":2,
         "Italy":0,
         "Spain":0,
         "Sweden":0,
         "UK":1,
         "Czech Republic":1,
         "Poland":1,
         "Russia":1,
         "Turkey":0,
         "Egypt":4,
         "South Africa":1,
         "Australia":1,
         "China":0,
         "India":3,
         "Indonesia":3,
         "Japan":3,
         "South Korea":3,
         "Taiwan":1,
         "Thailand":3
      }
   },
   {
      "Envrionmental pollution":{
         "Total Global":6,
         "USA ":0,
         "Canada":0,
         "Argentina":0,
         "Brazil ":0,
         "Mexico":0,
         "France":0,
         "Germany":0,
         "Italy":0,
         "Spain":0,
         "Sweden":0,
         "UK":0,
         "Czech Republic":0,
         "Poland":0,
         "Russia":0,
         "Turkey":0,
         "Egypt":0,
         "South Africa":0,
         "Australia":0,
         "China":2,
         "India":4,
         "Indonesia":0,
         "Japan":2,
         "South Korea":1,
         "Taiwan":0,
         "Thailand":2
      }
   },
   {
      "Wrongdoing by/corruption of elected officials":{
         "Total Global":8,
         "USA ":0,
         "Canada":0,
         "Argentina":0,
         "Brazil ":0,
         "Mexico":0,
         "France":0,
         "Germany":0,
         "Italy":0,
         "Spain":0,
         "Sweden":0,
         "UK":0,
         "Czech Republic":4,
         "Poland":0,
         "Russia":0,
         "Turkey":4,
         "Egypt":1,
         "South Africa":0,
         "Australia":0,
         "China":0,
         "India":0,
         "Indonesia":0,
         "Japan":4,
         "South Korea":0,
         "Taiwan":3,
         "Thailand":0
      }
   },
   {
      "Educational quality":{
         "Total Global":6,
         "USA ":4,
         "Canada":4,
         "Argentina":4,
         "Brazil ":0,
         "Mexico":0,
         "France":0,
         "Germany":0,
         "Italy":0,
         "Spain":0,
         "Sweden":0,
         "UK":0,
         "Czech Republic":0,
         "Poland":0,
         "Russia":0,
         "Turkey":2,
         "Egypt":0,
         "South Africa":0,
         "Australia":4,
         "China":3,
         "India":0,
         "Indonesia":0,
         "Japan":0,
         "South Korea":0,
         "Taiwan":4,
         "Thailand":0
      }
   },
   {
      "Cost of health care":{
         "Total Global":0,
         "USA ":0,
         "Canada":0,
         "Argentina":0,
         "Brazil ":0,
         "Mexico":0,
         "France":0,
         "Germany":0,
         "Italy":0,
         "Spain":0,
         "Sweden":0,
         "UK":0,
         "Czech Republic":0,
         "Poland":0,
         "Russia":0,
         "Turkey":0,
         "Egypt":0,
         "South Africa":0,
         "Australia":0,
         "China":0,
         "India":0,
         "Indonesia":0,
         "Japan":0,
         "South Korea":0,
         "Taiwan":0,
         "Thailand":0
      }
   },
   {
      "Future of retirement benefits provided by govt'":{
         "Total Global":0,
         "USA ":0,
         "Canada":0,
         "Argentina":0,
         "Brazil ":0,
         "Mexico":0,
         "France":0,
         "Germany":0,
         "Italy":0,
         "Spain":0,
         "Sweden":0,
         "UK":0,
         "Czech Republic":0,
         "Poland":0,
         "Russia":0,
         "Turkey":0,
         "Egypt":0,
         "South Africa":0,
         "Australia":0,
         "China":0,
         "India":0,
         "Indonesia":0,
         "Japan":0,
         "South Korea":0,
         "Taiwan":0,
         "Thailand":0
      }
   },
   {
      "Economic inequality":{
         "Total Global":0,
         "USA ":0,
         "Canada":0,
         "Argentina":0,
         "Brazil ":0,
         "Mexico":0,
         "France":0,
         "Germany":0,
         "Italy":0,
         "Spain":0,
         "Sweden":0,
         "UK":0,
         "Czech Republic":0,
         "Poland":0,
         "Russia":0,
         "Turkey":0,
         "Egypt":0,
         "South Africa":0,
         "Australia":0,
         "China":0,
         "India":0,
         "Indonesia":0,
         "Japan":0,
         "South Korea":0,
         "Taiwan":0,
         "Thailand":0
      }
   },
   {
      "Global climate change/global warming":{
         "Total Global":0,
         "USA ":0,
         "Canada":0,
         "Argentina":0,
         "Brazil ":0,
         "Mexico":0,
         "France":0,
         "Germany":0,
         "Italy":0,
         "Spain":0,
         "Sweden":0,
         "UK":0,
         "Czech Republic":0,
         "Poland":0,
         "Russia":0,
         "Turkey":0,
         "Egypt":0,
         "South Africa":0,
         "Australia":0,
         "China":0,
         "India":0,
         "Indonesia":0,
         "Japan":0,
         "South Korea":0,
         "Taiwan":0,
         "Thailand":0
      }
   },
   {
      "Personal information getting into wrong hands":{
         "Total Global":0,
         "USA ":0,
         "Canada":0,
         "Argentina":0,
         "Brazil ":0,
         "Mexico":0,
         "France":0,
         "Germany":0,
         "Italy":0,
         "Spain":0,
         "Sweden":0,
         "UK":0,
         "Czech Republic":0,
         "Poland":0,
         "Russia":0,
         "Turkey":0,
         "Egypt":0,
         "South Africa":0,
         "Australia":0,
         "China":0,
         "India":0,
         "Indonesia":0,
         "Japan":0,
         "South Korea":0,
         "Taiwan":0,
         "Thailand":0
      }
   },
   {
      "Terrorism":{
         "Total Global":10,
         "USA ":0,
         "Canada":0,
         "Argentina":0,
         "Brazil ":0,
         "Mexico":0,
         "France":0,
         "Germany":0,
         "Italy":0,
         "Spain":3,
         "Sweden":0,
         "UK":0,
         "Czech Republic":0,
         "Poland":0,
         "Russia":0,
         "Turkey":0,
         "Egypt":0,
         "South Africa":0,
         "Australia":0,
         "China":0,
         "India":0,
         "Indonesia":0,
         "Japan":0,
         "South Korea":0,
         "Taiwan":0,
         "Thailand":0
      }
   },
   {
      "Drug abuse":{
         "Total Global":4,
         "USA ":2,
         "Canada":0,
         "Argentina":0,
         "Brazil ":3,
         "Mexico":2,
         "France":0,
         "Germany":0,
         "Italy":0,
         "Spain":2,
         "Sweden":0,
         "UK":2,
         "Czech Republic":0,
         "Poland":3,
         "Russia":0,
         "Turkey":0,
         "Egypt":0,
         "South Africa":3,
         "Australia":2,
         "China":0,
         "India":0,
         "Indonesia":1,
         "Japan":0,
         "South Korea":0,
         "Taiwan":0,
         "Thailand":0
      }
   },
   {
      "Religious exptremism/fundamentalism":{
         "Total Global":11,
         "USA ":0,
         "Canada":0,
         "Argentina":0,
         "Brazil ":0,
         "Mexico":0,
         "France":0,
         "Germany":0,
         "Italy":0,
         "Spain":0,
         "Sweden":0,
         "UK":0,
         "Czech Republic":0,
         "Poland":0,
         "Russia":0,
         "Turkey":0,
         "Egypt":0,
         "South Africa":0,
         "Australia":0,
         "China":0,
         "India":0,
         "Indonesia":0,
         "Japan":0,
         "South Korea":0,
         "Taiwan":0,
         "Thailand":0
      }
   },
   {
      "Immigration":{
         "Total Global":13,
         "USA ":0,
         "Canada":0,
         "Argentina":0,
         "Brazil ":0,
         "Mexico":0,
         "France":0,
         "Germany":0,
         "Italy":0,
         "Spain":0,
         "Sweden":0,
         "UK":0,
         "Czech Republic":0,
         "Poland":0,
         "Russia":0,
         "Turkey":0,
         "Egypt":0,
         "South Africa":0,
         "Australia":0,
         "China":0,
         "India":0,
         "Indonesia":0,
         "Japan":0,
         "South Korea":0,
         "Taiwan":0,
         "Thailand":0
      }
   },
   {
      "Pandemics (epidemics that spread across world)":{
         "Total Global":0,
         "USA ":0,
         "Canada":0,
         "Argentina":0,
         "Brazil ":0,
         "Mexico":0,
         "France":0,
         "Germany":0,
         "Italy":0,
         "Spain":0,
         "Sweden":0,
         "UK":0,
         "Czech Republic":0,
         "Poland":0,
         "Russia":0,
         "Turkey":0,
         "Egypt":0,
         "South Africa":0,
         "Australia":0,
         "China":0,
         "India":0,
         "Indonesia":0,
         "Japan":0,
         "South Korea":0,
         "Taiwan":0,
         "Thailand":0
      }
   },
   {
      "Relations with foreing countries":{
         "Total Global":13,
         "USA ":0,
         "Canada":0,
         "Argentina":0,
         "Brazil ":0,
         "Mexico":0,
         "France":0,
         "Germany":0,
         "Italy":0,
         "Spain":0,
         "Sweden":0,
         "UK":0,
         "Czech Republic":0,
         "Poland":0,
         "Russia":0,
         "Turkey":0,
         "Egypt":0,
         "South Africa":0,
         "Australia":0,
         "China":0,
         "India":0,
         "Indonesia":0,
         "Japan":0,
         "South Korea":0,
         "Taiwan":0,
         "Thailand":0
      }
   },
   {
      "AIDS":{
         "Total Global":8,
         "USA ":0,
         "Canada":0,
         "Argentina":3,
         "Brazil ":4,
         "Mexico":3,
         "France":3,
         "Germany":0,
         "Italy":0,
         "Spain":1,
         "Sweden":0,
         "UK":0,
         "Czech Republic":0,
         "Poland":4,
         "Russia":0,
         "Turkey":0,
         "Egypt":2,
         "South Africa":2,
         "Australia":0,
         "China":0,
         "India":0,
         "Indonesia":2,
         "Japan":0,
         "South Korea":0,
         "Taiwan":0,
         "Thailand":0
      }
   },
   {
      "Relations between racial and ethnic groups":{
         "Total Global":11,
         "USA ":0,
         "Canada":0,
         "Argentina":0,
         "Brazil ":0,
         "Mexico":0,
         "France":0,
         "Germany":0,
         "Italy":0,
         "Spain":0,
         "Sweden":0,
         "UK":0,
         "Czech Republic":0,
         "Poland":0,
         "Russia":0,
         "Turkey":0,
         "Egypt":0,
         "South Africa":0,
         "Australia":0,
         "China":0,
         "India":0,
         "Indonesia":0,
         "Japan":0,
         "South Korea":0,
         "Taiwan":0,
         "Thailand":0
      }
   },
   {
      "Aid to countries in Third World":{
         "Total Global":15,
         "USA ":0,
         "Canada":0,
         "Argentina":0,
         "Brazil ":0,
         "Mexico":0,
         "France":0,
         "Germany":0,
         "Italy":0,
         "Spain":0,
         "Sweden":0,
         "UK":0,
         "Czech Republic":0,
         "Poland":0,
         "Russia":0,
         "Turkey":0,
         "Egypt":0,
         "South Africa":0,
         "Australia":0,
         "China":0,
         "India":0,
         "Indonesia":0,
         "Japan":0,
         "South Korea":0,
         "Taiwan":0,
         "Thailand":0
      }
   }
]